version: '3.9'

services:

  service-db:
    container_name: db
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main_db
    ports:
      - "5432:5432"
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "main_db" ]
#      interval: 5s
#      retries: 5
#    volumes:
#      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  prom_data:

