services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - SERVER_PORT=8000
        depends_on:
            - service-db
